### ISSUE TITLE
Tensorflow Hub

### ISSUE THREAD

**Issue by junxnone** [junxnone/tio#106]
#93 
# Reference
- [ ] [Hub guide](https://www.tensorflow.org/hub/)
- [ ] [Github repo](https://github.com/tensorflow/hub)
- [ ] [tfhub](https://tfhub.dev/)
- [ ] [Introducing TensorFlow Hub: A Library for Reusable Machine Learning Modules in TensorFlow](https://medium.com/tensorflow/introducing-tensorflow-hub-a-library-for-reusable-machine-learning-modules-in-tensorflow-cdee41fa18f9)
- [ ] [Hub API](https://www.tensorflow.org/hub/api_docs/python/hub)
- [ ] [利用tensorflow的image_retrain实现再训练和分类识别](https://blog.csdn.net/daydayup_668819/article/details/79972886)

# TO-DO

[Google colab](https://github.com/tensorflow/hub/tree/master/examples/colab)
- [ ] action_recognition_with_tf_hub.ipynb
- [ ] object_detection.ipynb
- [ ] semantic_similarity_with_tf_hub_universal_encoder.ipynb
- [ ] semantic_similarity_with_tf_hub_universal_encoder_lite.ipynb
- [ ] text_classification_with_tf_hub.ipynb
- [ ] text_classification_with_tf_hub_on_kaggle.ipynb
- [ ] tf_hub_delf_module.ipynb
- [ ] tf_hub_generative_image_module.ipynb

# Examples
## Object detection

# Term
Bottlenecks - 非正式称呼 image feature vector
