### ISSUE TITLE
PAIR - People + AI Research

### ISSUE THREAD

**Issue by junxnone** [junxnone/tio#221]
# Reference
- [ ] [People + AI Research (PAIR)](https://ai.google/research/teams/brain/pair)
  - [ ] [PAIR Github](https://github.com/PAIR-code)
- [ ] [Facets](https://pair-code.github.io/facets/)
  - [ ] [Facets Github repo](https://github.com/pair-code/facets)
  - [ ] [Facets: An Open Source Visualization Tool for Machine Learning Training Data](https://ai.googleblog.com/2017/07/facets-open-source-visualization-tool.html)
  - [ ] [使用谷歌 FACETS 可视化机器学习数据集](https://github.com/xitu/gold-miner/blob/master/TODO1/visualising-machine-learning-datasets-with-googles-facets.md)
  - [ ] [CarvanaImageMasking - facets_visualization.ipynb](https://github.com/vfdev-5/CarvanaImageMasking/blob/stale/notebooks/facets_visualization.ipynb)
  - [ ] [Providing Sprites For Dive to Render](https://github.com/PAIR-code/facets/tree/master/facets_dive#providing-sprites-for-dive-to-render)
- [ ] [Embedding Projector](https://projector.tensorflow.org/)
  - [ ] [word_embeddings.ipynb](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/text/word_embeddings.ipynb)

# Facets
Facets 是谷歌为了支持 PAIR (People + AI Research) 项目而发布的一个开源可视化工具，可以帮助我们理解和分析机器学习数据集
## Facets Overview
提供了整个数据集的概览和数据每项特征的分布情况， 并比较了训练和测试数据集
![image](https://user-images.githubusercontent.com/2216970/69931797-880f2300-1503-11ea-93d1-0d11abe3db87.png)

## Facets Dive
帮助用户深入理解数据的单个特征，并通过观察单个特征获取更多信息。它有助于一次性交互式地探索大量数据点
- 单变量分析
- 双变量分析
![image](https://user-images.githubusercontent.com/2216970/69931878-d91f1700-1503-11ea-950d-8cc996309d77.png)

---
image dataset的应用
使用 Confusion matrix 的方式显示数据，可以很快的查看Ground truth 是否label的正确
![image4](https://user-images.githubusercontent.com/2216970/69937183-fd372400-1514-11ea-8dc3-e8f6e904136c.gif)

# Embedding Projector

**Comment by junxnone** [comment]
# TO-DO
- [ ] Test local host: [CarvanaImageMasking - facets_visualization.ipynb](https://github.com/vfdev-5/CarvanaImageMasking/blob/stale/notebooks/facets_visualization.ipynb)
