### ISSUE TITLE
COCO Dataset - cocoapi

### ISSUE THREAD

**Issue by junxnone** [junxnone/tio#257]
> This package provides Matlab, Python, and Lua APIs that assists in loading, parsing, and visualizing the annotations in COCO. 

# Reference
- [ ] [Github repo](https://github.com/cocodataset/cocoapi)
- [ ] [Dataset](http://cocodataset.org/)

# Build
```
git clone https://github.com/cocodataset/cocoapi.git
cd cocoapi/PythonAPI
make
cp -rf pycocotools/ /your/path/
```

**Comment by junxnone** [comment]
#244 

**TODO**
- [ ] [evaluation](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py)
- [ ] Read image info
- [ ] Read annotation info
- [ ] Summary annotation info
  - category
  - ROIs(small/medium/large)
