### ISSUE TITLE
Detectron - Detectron2

### ISSUE THREAD

**Issue by junxnone** [junxnone/tio#339]
# Reference
- [ ] [detectron2 - FAIR](https://github.com/facebookresearch/detectron2)
- [ ] [Docs](https://detectron2.readthedocs.io/index.html)
- [ ] [TACO using Detectron2.ipynb](https://colab.research.google.com/drive/1DIk7bDpdZDkTTZyJbPADZklcbZKr1xkn#scrollTo=MxEIwdaJHZR8)

#  Brief
Name | implementations
-- | --
Detectron | Caffe2
maskrcnn-benchmark | PyTorch 1.0
Detectron2 |  PyTorch ≥ 1.4

# Environment
## Docker 使用
```
git clone https://github.com/facebookresearch/detectron2.git
cd  detectron2/docker
docker-compose run detectron2
```

## Host Virtualenv
```
mkvirtualenv -p python3 pytorch
pip3 install torch==1.3.1+cu92 torchvision==0.4.2+cu92 -f https://download.pytorch.org/whl/torch_stable.html
pip3 install cython
pip3 install -U 'git+https://github.com/facebookresearch/fvcore.git' 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
pip3 install -e detectron2/
```
> N.B. GCC/G++ 要用 4.9

## [Config](https://detectron2.readthedocs.io/tutorials/configs.html)

- add new config
```
from detectron2.config import get_cfg
cfg = get_cfg() 
cfg.xxx = yyy     
```
> cfg is [CfgNode](https://detectron2.readthedocs.io/modules/config.html#detectron2.config.CfgNode) Instance
- load from config yaml file
```
cfg.merge_from_file("my_cfg.yaml")   
```
- load from list
```
cfg.merge_from_list(["MODEL.WEIGHTS", "weights.pth"])  
```
- dump configs
```
print(cfg.dump())  
```
> [all configs name](https://detectron2.readthedocs.io/modules/config.html#config-references)

## [Data](https://detectron2.readthedocs.io/tutorials/datasets.html)
- register dataset
```
def get_dicts():
  ...
  return list[dict] in the following format

from detectron2.data import DatasetCatalog
DatasetCatalog.register("my_dataset", get_dicts)
```
- register metadata

**Comment by junxnone** [comment]
#291 #465 #213 

# TODO
- [x] Configs
- [ ]  DataLoader
- [ ] Save checkpoint / model
- [ ] Evaluation
- [ ] Tuning model
- [ ] Test different model
