### ISSUE TITLE
tensorflow.js - webcam-transfer-learning

### ISSUE THREAD

**Issue by junxnone** [junxnone/tio#356]
#355 

> In this tutorial, we will use transfer learning to predict user-defined classes from webcam data (poses, objects, facial expressions, etc) and play Pacman by assigning each of those poses to "up", "down", "left", and "right".

# Reference
- [ ] [Transfer learning - Train a neural network to predict from webcam data](https://js.tensorflow.org/tutorials/webcam-transfer-learning.html)
- [ ] [webcam-transfer-learning](https://storage.googleapis.com/tfjs-examples/webcam-transfer-learning/dist/index.html)
# TO-DO
- [ ] 使用tensorflow.js 做一个web端的online learning 应用

# Set env
```
git clone https://github.com/tensorflow/tfjs-examples
cd tfjs-examples/webcam-transfer-learning
yarn
yarn watch
```
http://127.0.0.1:1234
> chrome 不允许http访问webcam 。所以linux机器开了server，win却不能访问

**Comment by junxnone** [comment]
#70 #407
